services:
  animux:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "C:/Users/User/Downloads:/source:ro"
      - "C:/Users/User/Downloads:/destination:rw"
    environment:
      - SOURCE_DIR=/source
      - DEST_DIR=/destination
    restart: unless-stopped
